### ISSUE TITLE
Illegal Request when running sg_raw command

### ISSUE THREAD

**Issue by acarlstein** [SofianeHamlaoui/WD-Decrypte#2]
First, I would like to thank Sofiane for posting this. It gives me some hope.

Second, do anyone knows why I am getting this message and how I could go around it?
I run out of options in my searches.

```
root@ubuntu:/home/ubuntu/Desktop# sudo sg_raw -v -s 40 -i ./password.bin /dev/sdc c1 e1 00 00 00 00 00 00 28 00
    cdb to send: c1 e1 00 00 00 00 00 00 28 00 
SCSI Status: Check Condition 

Sense Information:
Fixed format, current; Sense key: Illegal Request
ASC=74, vendor specific qualification ASCQ=81 (hex)
 Raw sense data (in hex):
        70 00 05 00 00 00 00 0a  00 00 00 00 74 81 00 00
        00 00

Illegal request
```
I am working on a WD Password 25E2.

GParted shows:
![screenshot from 2018-12-09 18-30-03](https://user-images.githubusercontent.com/5709926/49701162-95d7e400-fbe0-11e8-876c-dc8a359af69e.png)

**Comment by SofianeHamlaoui** [comment]
Hi Alejandro , thanks for sharing you issue here so it can help others with you. 
in your command you typed /dev/sdc ? but as i see here on the picture you shared ,  /dev/sdc is the hard drive you installed ubuntu on  , knowing that the tool i shared is to unlock the EXTERNAL WD hard drives ? are you sure that the /dev/sdc is the WD HD ?

**Comment by acarlstein** [comment]
@SofianeHamlaoui , I am sure its in sdc because the WD Password is the only one with 4TB of size.

![screenshot](https://user-images.githubusercontent.com/5709926/49701513-3d571580-fbe5-11e8-9f97-92367cafa36b.png)

I am running Ubuntu from the CD rom without installing it.

**Comment by acarlstein** [comment]
Is there a way that you could share how the partition of the external WD drive should look like?
Perhaps this is an issue related with the type of partitions used.

**Comment by SofianeHamlaoui** [comment]
can you share with me the output of your ' lsblk ' command ? 
also , as i'm seeing on the picture you shared you already have an os installed on the hard drive ? ( correct me if i'm worng ! ) 
and just to make it clear for you ! this tool i shared is a replacement for the WD security on windows.
please explain more what you want to do with the HDD so i can help you
