### ISSUE TITLE
Unlock Westerne Digital

### ISSUE THREAD

**Issue by mafalda771** [SofianeHamlaoui/WD-Decrypte#4]
Hi,

Thank you for the tutotial : https://www.youtube.com/watch?v=Qz51UelzByA
I have an issue with the creation of the file passord.bin
The file is empty (0 bytes) but you mentioned that the file should be 40 bytes

I still tried to proceed with the other commands. And on the last command, I received the following error message :
/dev/sdd: No such file or directory

**Comment by SofianeHamlaoui** [comment]
Hi there @mafalda771 , 
First of all , both errors are normal , because to generate the password.bin file you have to inter a valid device name !
to solve that ! can you share with me the output of your ' lsblk ' command ?

**Comment by mafalda771** [comment]
Hi Sofiane,

Here is the output ' lsblk ':
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 465,8G  0 disk 
└─sda1   8:1    0 465,8G  0 part /media/mafalda/668690EA1950E
sdb      8:16   0 119,2G  0 disk 
├─sdb1   8:17   0   512M  0 part /boot/efi
├─sdb2   8:18   0 110,9G  0 part /
└─sdb3   8:19   0   7,9G  0 part [SWAP]
sdc      8:32   0 931,5G  0 disk 
sr0     11:0    1    30M  0 rom  /media/mafalda/WD Unlocker


I think I managed to create the passport.bin file, this time with 40 bytes.

Then I try the last command : "sudo sg_raw -s 40 -i password.bin /dev/sdc c1 e1 00 00 00 00 00 00 28 00"

At the beginning I recieved, the output "SCSI Status: Good", but I still could not access to the drive.

Then, when I try again, I get the following output :
SCSI Status: Check Condition 

Sense Information:
 Fixed format, current;  Sense key: Illegal Request
 ASC=74, vendor specific qualification ASCQ=81 (hex)

**Comment by SofianeHamlaoui** [comment]
So, lets start from the beginning !

You received "SCSI Status: Good" means the tool worked perfectly, Now are you sure the drive is working perfectly ?
also, you can't try that command twice at the same time, when the output is "SCSI Status: Good" all you have is to mount the drive and that's it  (sudo mount /dev/sdc)

**Comment by mafalda771** [comment]
The drive works perfectly on windows, and no issue to lock or unlock it from windows.

I tried again on linux, and received the correct output "SCSI Status: Good"

When I try to mount the drive using the command "sudo mount /dev/sdc"
I receive the output :"impossible to find /dev/sdc in /etc/fstab or /etc/mtab"

**Comment by SofianeHamlaoui** [comment]
Aw ! After receiving the correct output, try an 'lsblk' command and send me the output.

**Comment by mafalda771** [comment]
Here is the output

NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 465,8G  0 disk 
└─sda1   8:1    0 465,8G  0 part 
sdb      8:16   0 119,2G  0 disk 
├─sdb1   8:17   0   512M  0 part /boot/efi
├─sdb2   8:18   0 110,9G  0 part /
└─sdb3   8:19   0   7,9G  0 part [SWAP]
sdc      8:32   0 931,5G  0 disk 
sr0     11:0    1    30M  0 rom  /media/mafalda/WD Unlocker

**Comment by mafalda771** [comment]
Ok, so I tried something else. I restarted the computer after having received the correct "SCSI Status : Good" output. And the drive appears instantly this time. I can access to it with no problem.

Then, if a restart the computer one more time, it disappear. 

At least, I found a way to access to the drive!
Do you have any idea why it requires to restart after the last command?

**Comment by SofianeHamlaoui** [comment]
Hi ! In the YouTube video you can see that just after SCSI Status : Good" output you can access the drive directly without a restart, means the drive appears directly on your file manager.
When you restart the computer you have to do the commands again, that's why i shared with the repo a (bash) [HERE](https://github.com/SofianeHamlaoui/WD-Decrypte/blob/master/drive.sh) to automate that!
(you can add that to your startup session so it starts at the same time with the window manager you use.
![5555555555555555555555555](https://user-images.githubusercontent.com/16967174/60759940-439f5a00-a02d-11e9-8760-df409611bfee.png)

**Comment by mafalda771** [comment]
Hi!

Indeed I saw on the video that you can access to the drive straight after the SCSI Status : Good output.
And I understand that you have to do the commands again when you restart the computer.

The weird thing on my side is that when I get the "SCSI Status : Good" output :
- the drive does not appear on my file manager
- the "sudo mount /dev/sdc" command get the "impossible to find /dev/sdc in /etc/fstab or /etc/mtab" output
- the "lsblk" command get the "sdc 8:32 0 931,5G 0 disk" output

However, if I restart my computer straight after the "SCSI Status : Good" output, then the drive appears in my file manager !
I can access to it, and the lsblk command receives the following output :  

NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 465,8G  0 disk 
└─sda1   8:1    0 465,8G  0 part 
sdb      8:16   0 119,2G  0 disk 
├─sdb1   8:17   0   512M  0 part /boot/efi
├─sdb2   8:18   0 110,9G  0 part /
└─sdb3   8:19   0   7,9G  0 part [SWAP]
sdc      8:32   0 931,5G  0 disk 
└─sdc1   8:33   0 931,5G  0 part /media/mafalda/My Passport1
sr0     11:0    1    30M  0 rom  /media/mafalda/WD Unlocker

Then, if I restart one more time the computer, the drive disappears and I have to start again the "sudo sg_raw -s 40 -i password.bin /dev/sdc c1 e1 00 00 00 00 00 00 28 00" command and restart the computer once. 

This is fine for me. At least it works. I just wonder why I have to restart after the "SCSI Status : Good" output in order to make the drive appear...

**Comment by SofianeHamlaoui** [comment]
@mafalda771 Hi , Tell me ? 
Are you using Xfce ? 
Try to install these 2 packages : gvfs and thunar-volman ( sudo pacman -S gvfs thunar-volman )
restart you pc and do that again !

**Comment by mafalda771** [comment]
Hi Sofiane,
I do not know what Xfce is, so I am probably not using it ;)
 
Anyway, I do not want to waste too much your time... Your tuto and support helped me already a lot ! Thank you for that. :D

**Comment by SofianeHamlaoui** [comment]
No worries man,
You are welcomed to open another issue anytime you have any problems concerning that.
Have a nice day.
( closing the issue )

**Comment by sergiigladchuk** [comment]
Hi,
Your initial command after unlocking drive:
`sudo mount /dev/sdc`

was not correct. You should have used:

`sudo mount /dev/sdc1`

since after unlocking drive, first and usually only partition is visible to the system and that is the device you want to mount not `sdc`.

**Comment by sergiigladchuk** [comment]
I have got the same problem with unlocking my WD drives:

```
SCSI Status: Check Condition

Sense Information:
Fixed format, current; Sense key: Illegal Request
```

And I do not really want to restart my system all the time. And it does not really help to solve the problem. I still can access my drive from other linux PC, so I do not really know why I cannot unlock the drive from the initial PC.
Any guesses? Anything which can help in my case?
