### ISSUE TITLE
Pb derniere etape- authentification failed

### ISSUE THREAD

**Issue by cherifguess** [SofianeHamlaoui/WD-Decrypte#7]
Salam ,

Bravo pour le partage!! J ai bloqué mon disque dur avec toutes mes photos depuis des décennies.. et je cherche désespérément à accéder à mon WD MYPASSPORT. J ai suivi la marche à suivre et merci !! Sauf qu'à la dernière étape je suis bloqué voici "authentification failed" "illégal request". Je suis en live usb ....comment pourrais je stp le résoudre?  Merci mille fois !! En photo mon souci  @screenshot
![20200419_011456](https://user-images.githubusercontent.com/63934752/79673787-19deaa80-81dd-11ea-9ff0-97f61fcfa6ed.jpg)

**Comment by Rom1Linux** [comment]
> Salam ,
> 
> Bravo pour le partage!! J ai bloqué mon disque dur avec toutes mes photos depuis des décennies.. et je cherche désespérément à accéder à mon WD MYPASSPORT. J ai suivi la marche à suivre et merci !! Sauf qu'à la dernière étape je suis bloqué voici "authentification failed" "illégal request". Je suis en live usb ....comment pourrais je stp le résoudre? Merci mille fois !! En photo mon souci @screenshot
> ![20200419_011456](https://user-images.githubusercontent.com/63934752/79673787-19deaa80-81dd-11ea-9ff0-97f61fcfa6ed.jpg)

Salut, je m'intéresse à ce problème justement pour le disque d'une amie. Déjà avec un live CD, je pense qu'il y a pas toutes les dépendances nécessaires d'installé. As-tu bien réussi à installer sg3_utils ? Au vu du message d'erreur je dirai qu'il y a un problème sur le fichier password.bin

**Comment by akashkmr** [comment]
I am having same issue, any way to solve this?
