### ISSUE TITLE
Error on running sudo sg_raw -s 40 -i password.bin /dev/sda c1 e1 00 00 00 00 00 00 28 00 command

### ISSUE THREAD

**Issue by cclcyber** [SofianeHamlaoui/WD-Decrypte#9]
Hi there

When i try to run this command i receive the following error:

SCSI Status: Check Condition - 
Sense Information: Fixed format, current; Sense key: Illegal Request- Additional sense: Invalid command operation code". 

I´m sure that dev is sda. Any idea?

Thanks.

**Comment by mian-muhammad-mubasher** [comment]
I followed the procedure today, it worked just fine for me.

**Comment by jittygitty** [comment]
@cclcyber I have the same problem. What kernel version was your system? ie output of uname -a ? I have found that on older linux systems where dmesg | grep -i "scsi" or dmesg | grep -i "Type" shows the drive detected as "Type 0" will not work.

But on newer Linux kernels where it is detected as "Type 13", it will work.
